### ISSUE TITLE
Using with npm enterprise

### ISSUE THREAD

**Issue by gciluffo** [npm/registry-follower-tutorial#8]
I am currently working with our companies own private npm enterprise registry. I have code very similar to this repo but the changes-stream library is returning a 404 for the couch db. However I am getting the registry data in the response body. Here is the output

``` 
body {"db_name":"registry","doc_count":10,"doc_del_count":0,"update_seq":95,"purge_seq":0,"compact_running":false,"disk_size":1347688,"data_size":129773,"instance_start_time":"1510780609538097","disk_format_version":6,"committed_update_seq":95}
error null
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Received a 404 from couch
    at ChangesStream._onResponse (/Users/griffin/sandbox/registry-follower-tutorial/node_modules/changes-stream/index.js:155:15)
    at Object.onceWrapper (events.js:314:30)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:549:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:438:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
```
This approach with `changes-stream` should work with enterprise registries since it is still using couch DB right? Currently our registry is running in a Docker container on a VM.
 
Any suggestions would be much appreciated! Thanks

**Comment by ashleygwilliams** [comment]
oh this is a very interesting question @gciluffo ! sorry for the delay, i'll talk to my colleagues and see if i can figure out what's up. i would suspect it should work but i can also imagine a few spots that might make it tricky. i'll let you know what i figure out!

cc @bcoe @arobson

**Comment by gciluffo** [comment]
I got it working. But I had to write the service in the VM where the npm couch db lives. And then used forever/npm to run it.
